CREATE TABLE "product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar,
  "description" text,
  "sku" integer,
  "category" varchar,
  "price" integer,
  "discount_id" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "discount" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar,
  "description" text,
  "percent" integer,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "cart_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "session_id" integer,
  "product_id" integer,
  "quantity" integer,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "shopping_session" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "total" integer,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" integer,
  "product_id" integer,
  "created_at" datetime,
  "modified_at" timestamp
);

CREATE TABLE "order_details" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "total" integer,
  "payment_id" integer UNIQUE,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" integer,
  "amount" integer,
  "status" varchar,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar,
  "email" varchar,
  "password" text,
 "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE "product" ADD FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("session_id") REFERENCES "shopping_session" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "shopping_session" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "order_details" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "payment" ADD FOREIGN KEY ("order_id") REFERENCES "order_details" ("id");
