

CREATE TABLE users (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" text NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE discount (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "percent" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE product (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "sku" integer UNIQUE,
  "category" varchar(100),
  "price" numeric(10, 2),
  "discount_id" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE shopping_session (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "total" numeric(10, 2),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE cart_item (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "session_id" integer,
  "product_id" integer,
  "quantity" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE payment (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" integer,
  "amount" numeric(10, 2),
  "status" varchar(20) CHECK ("status" IN ('pending', 'completed', 'failed')) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE order_details (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "total" numeric(10, 2),
  "payment_id" integer UNIQUE,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE order_items (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" integer,
  "product_id" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "modified_at" timestamp DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "product" ADD FOREIGN KEY ("discount_id") REFERENCES "discount" ("id") ON DELETE SET NULL;
ALTER TABLE "cart_item" ADD FOREIGN KEY ("session_id") REFERENCES "shopping_session" ("id") ON DELETE CASCADE;
ALTER TABLE "cart_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE;
ALTER TABLE "shopping_session" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "order_details" ("id") ON DELETE CASCADE;
ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE;
ALTER TABLE "order_details" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "payment" ADD FOREIGN KEY ("order_id") REFERENCES "order_details" ("id") ON DELETE CASCADE;
